import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Raleway } from "next/font/google";
const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "IRCTC - Topic Minings",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
